export enum EventLoggingEnum {
  ENQUIRY_UPDATE_NOP_INITIATED = 'ENQUIRY_UPDATE_NOP_INITIATED',
  ENQUIRY_UPDATE_NOP_FAILED = 'ENQUIRY_UPDATE_NOP_FAILED',
  ENQUIRY_UPDATE_NOP_SUCCESSFUL = 'ENQUIRY_UPDATE_NOP_SUCCESSFUL',
}