export enum EventLoggingEnum {
  ENQUIRY_UPDATE_NOP_INITIATED = 'ENQUIRY_UPDATE_NOP_INITIATED',
  ENQUIRY_UPDATE_NOP_INITIATED_FOR_RECORD_ID = 'ENQUIRY_UPDATE_NOP_INITIATED_FOR_RECORD_ID',
  ENQUIRY_UPDATE_NOP_FAILED = 'ENQUIRY_UPDATE_NOP_FAILED',
  ENQUIRY_UPDATE_NOP_SUCCESSFUL = 'ENQUIRY_UPDATE_NOP_SUCCESSFUL',
}